package com.startuphub.enums;

public enum NotificationType {
    REQUEST_SUBMITTED, REQUEST_ASSIGNED, REQUEST_UPDATED,
    COMPLETED, REJECTED, CANCELLED,
    PAYMENT_DUE, PAYMENT_RECEIVED, INVOICE_GENERATED, REFUND_PROCESSED,
    SLA_WARNING, SLA_BREACHED,
    LEAVE_APPROVED, LEAVE_REJECTED, PAYSLIP_READY, LETTER_ISSUED,
    WELCOME, TEAM_INVITE, ANNOUNCEMENT,
    GENERAL
}
