# ─── Dev Profile ───────────────────────────────────────────────────────────
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.com.saas.luminex=DEBUG
logging.level.org.springframework.security=DEBUG
